releases:
- name: kafka
  namespace: prod
  chart: oci://registry-1.docker.io/bitnamicharts/kafka
  version: 25.3.5
  set:
  - name: broker.replicaCount
    value: 5
  - name: listeners.client.protocol 
    value: SASL_PLAINTEXT
  - name: listeners.interbroker.protocol 
    value: SASL_PLAINTEXT
