apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-operator
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: ["otus.homework"]
  resources: ["mysqls"]
  verbs: ["patch","list","watch"]
- apiGroups: [""]
  resources: ["persistentvolumes","persistentvolumeclaims"]
  verbs: ["create","delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","create","delete"]
- apiGroups: ["apps"]
  resources: ["deployments/status"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create","delete"]
