apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  labels:
    app: mysql-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
    spec:
      serviceAccount: mysql-operator
      containers:
      - name: mysql-operator
        image: roflmaoinmysoul/mysql-operator:1.0.0 
