{{ if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.clusterRoleName }}
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
{{ end }}
