apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: web-server
    spec:
      serviceAccount: monitoring
      initContainers:
      - name: init-page
        image: busybox:1.36.1
        command: ['sh', '-c', 'wget https://www.rancher.com/ -O /init/index.html']
        volumeMounts:
        - name: homework-volume
          mountPath: /init
      containers:
      - name: nginx-container
        image: nginx:1.29
        ports:
        - containerPort: 8000
          name: http
        lifecycle:
          preStop:
            exec:
              command: ['sh', '-c', 'rm', '/homework/index.html']
        volumeMounts:
        - name: homework-volume
          mountPath: /homework
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8000
          initialDelaySeconds: 1
          periodSeconds: 5
      - name: metrics-storer
        image: alpine/curl:8.1.2
        volumeMounts:
        - name: homework-volume
          mountPath: /homework
        - name: script-config
          mountPath: /app
          readOnly: true
        command: ['sh', '/app/store-metrics.sh']
      volumes:
      - name: homework-volume
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: config
          items:
          - key: default.conf
            path: default.conf
      - name: script-config
        configMap:
          name: config
          defaultMode: 0777
          items:
          - key: store-metrics.sh
            path: store-metrics.sh
