apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: web-server
    spec:
      initContainers:
      - name: init-page
        image: busybox:1.36.1
        command: ['sh', '-c', 'wget https://www.rancher.com/ -O /init/index.html']
        volumeMounts:
        - name: homework-volume
          mountPath: /init
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
      containers:
      - name: nginx-container
        image: nginx:1.29
        ports:
        - containerPort: 8000
          name: http
        lifecycle:
          preStop:
            exec:
              command: ['sh', '-c', 'rm', '/homework/index.html']
        volumeMounts:
        - name: homework-volume
          mountPath: /homework
        - name: config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: config-pairs
          mountPath: /homework/conf
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8000
          initialDelaySeconds: 1
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
      volumes:
      - name: homework-volume
        persistentVolumeClaim:
          claimName: web-server
      - name: config
        configMap:
          name: nginx-config
          items:
          - key: default.conf
            path: default.conf
      - name: config-pairs
        configMap:
          name: nginx-config
          items:
          - key: key
            path: key
          - key: someKey
            path: someKey
