apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-server
  namespace: homework
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: custom-sc
  resources:
    requests:
      storage: 200Mi
