apiVersion: v1
kind: Pod
metadata:
  name: web-server
  namespace: homework
spec:
  initContainers:
  - name: init-page
    image: busybox:1.36.1
    command: ['sh', '-c', 'wget https://www.rancher.com/ -O /init/index.html']
    volumeMounts:
    - name: homework-volume
      mountPath: /init
  containers:
  - name: nginx-container
    image: nginx:1.29
    ports:
    - containerPort: 8000
    lifecycle:
      preStop:
        exec:
          command: ['sh', '-c', 'rm', '/homework/index.html']
    volumeMounts:
    - name: homework-volume
      mountPath: /homework
    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true
  volumes:
  - name: homework-volume
    emptyDir: {}
  - name: config
    configMap:
      name: nginx-config
      items:
      - key: default.conf
        path: default.conf
